# Header
menu:
  Home: /
  About: /about
  Katas: /katas	
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: 
widgets:
#- recent_posts
# - twitter

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: jnonnen
google_plus:
fb_admins:
fb_app_id:
